/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryIndexRouteImport } from './routes/story.index'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as StoryProjectIdIndexRouteImport } from './routes/story.$projectId.index'
import { Route as StoryProjectIdTemplateIdRouteImport } from './routes/story.$projectId.$templateId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIndexRoute = StoryIndexRouteImport.update({
  id: '/story/',
  path: '/story/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryProjectIdIndexRoute = StoryProjectIdIndexRouteImport.update({
  id: '/story/$projectId/',
  path: '/story/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryProjectIdTemplateIdRoute =
  StoryProjectIdTemplateIdRouteImport.update({
    id: '/story/$projectId/$templateId',
    path: '/story/$projectId/$templateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/sign-in': typeof SignInRoute
  '/api/upload': typeof ApiUploadRoute
  '/story/': typeof StoryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/story/$projectId/$templateId': typeof StoryProjectIdTemplateIdRoute
  '/story/$projectId/': typeof StoryProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/sign-in': typeof SignInRoute
  '/api/upload': typeof ApiUploadRoute
  '/story': typeof StoryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/story/$projectId/$templateId': typeof StoryProjectIdTemplateIdRoute
  '/story/$projectId': typeof StoryProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/sign-in': typeof SignInRoute
  '/api/upload': typeof ApiUploadRoute
  '/story/': typeof StoryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/story/$projectId/$templateId': typeof StoryProjectIdTemplateIdRoute
  '/story/$projectId/': typeof StoryProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/sign-in'
    | '/api/upload'
    | '/story/'
    | '/api/auth/$'
    | '/story/$projectId/$templateId'
    | '/story/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/sign-in'
    | '/api/upload'
    | '/story'
    | '/api/auth/$'
    | '/story/$projectId/$templateId'
    | '/story/$projectId'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/sign-in'
    | '/api/upload'
    | '/story/'
    | '/api/auth/$'
    | '/story/$projectId/$templateId'
    | '/story/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  SignInRoute: typeof SignInRoute
  ApiUploadRoute: typeof ApiUploadRoute
  StoryIndexRoute: typeof StoryIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  StoryProjectIdTemplateIdRoute: typeof StoryProjectIdTemplateIdRoute
  StoryProjectIdIndexRoute: typeof StoryProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/': {
      id: '/story/'
      path: '/story'
      fullPath: '/story/'
      preLoaderRoute: typeof StoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$projectId/': {
      id: '/story/$projectId/'
      path: '/story/$projectId'
      fullPath: '/story/$projectId/'
      preLoaderRoute: typeof StoryProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$projectId/$templateId': {
      id: '/story/$projectId/$templateId'
      path: '/story/$projectId/$templateId'
      fullPath: '/story/$projectId/$templateId'
      preLoaderRoute: typeof StoryProjectIdTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  SignInRoute: SignInRoute,
  ApiUploadRoute: ApiUploadRoute,
  StoryIndexRoute: StoryIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  StoryProjectIdTemplateIdRoute: StoryProjectIdTemplateIdRoute,
  StoryProjectIdIndexRoute: StoryProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
